/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-04-18 08:41:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsHotelDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1675145507184L));
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675145505448L));
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>호텔 상세 페이지</title>\r\n");
      out.write("    <script src = \"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <!-- CSS only -->\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("   <!-- jQuery 라이브러리 -->\r\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <!-- Popper.js 라이브러리 -->\r\n");
      out.write("   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <!-- Bootstrap JS -->\r\n");
      out.write("   <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("     $(document).ready(function() {\r\n");
      out.write("       $(\"#datepicker1\").datepicker({\r\n");
      out.write("         dateFormat: \"yy-mm-dd\"\r\n");
      out.write("       });\r\n");
      out.write("     });\r\n");
      out.write("   </script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      function add_cart(goods_code) {\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            type : \"post\",\r\n");
      out.write("            async : false, //false인 경우 동기식으로 처리한다.\r\n");
      out.write("            /* Ajax를 이용해 장바구니에 추가할 상품 번호를 전송합니다. */\r\n");
      out.write("            url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/addGoodsInCart.do\",\r\n");
      out.write("            data : {\r\n");
      out.write("               goods_code:goods_code\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("            },\r\n");
      out.write("            success : function(data, textStatus) {\r\n");
      out.write("               //alert(data);\r\n");
      out.write("            //   $('#message').append(data);\r\n");
      out.write("            /* 장바구니에 추가하면 알림창을 표시 */\r\n");
      out.write("               if(data.trim()=='add_success'){\r\n");
      out.write("                  imagePopup('open', '.layer01');   \r\n");
      out.write("                  alert(\"장바구니에 담았습니다.\");\r\n");
      out.write("               }else if(data.trim()=='already_existed'){\r\n");
      out.write("                  alert(\"이미 카트에 등록된 상품입니다. 장바구니로 이동합니다.\");\r\n");
      out.write("                  location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cartList.do\";\r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("            },\r\n");
      out.write("            error : function(data, textStatus) {\r\n");
      out.write("               alert(\"로그인 후 이용해주세요.\");\r\n");
      out.write("               location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/joinAndLogin/loginForm.do\";\r\n");
      out.write("            },\r\n");
      out.write("            complete : function(data, textStatus) {\r\n");
      out.write("               //alert(\"작업을완료 했습니다\");\r\n");
      out.write("            }\r\n");
      out.write("         }); //end ajax   \r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("      function imagePopup(type) {\r\n");
      out.write("         if (type == 'open') {\r\n");
      out.write("            // 팝업창을 연다.\r\n");
      out.write("            jQuery('#layer').attr('style', 'visibility:visible');\r\n");
      out.write("   \r\n");
      out.write("            // 페이지를 가리기위한 레이어 영역의 높이를 페이지 전체의 높이와 같게 한다.\r\n");
      out.write("            jQuery('#layer').height(jQuery(document).height());\r\n");
      out.write("         }\r\n");
      out.write("   \r\n");
      out.write("         else if (type == 'close') {\r\n");
      out.write("   \r\n");
      out.write("            // 팝업창을 닫는다.\r\n");
      out.write("            jQuery('#layer').attr('style', 'visibility:hidden');\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("   function fn_order_each_goods(goods_code,goods_name,goods_price,goods_saleprice,goods_category){\r\n");
      out.write("      var _isLogOn=document.getElementById(\"isLogOn\");\r\n");
      out.write("      var isLogOn=_isLogOn.value;\r\n");
      out.write("      \r\n");
      out.write("       if(isLogOn==\"false\" || isLogOn=='' ){\r\n");
      out.write("         alert(\"로그인 후 이용해주세요.\");\r\n");
      out.write("      } \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("         var total_price,final_total_price;\r\n");
      out.write("         /* var order_headcount=document.getElementById(\"order_headcount\"); */\r\n");
      out.write("         \r\n");
      out.write("         var formObj=document.createElement(\"form\");\r\n");
      out.write("         var i_goods_code = document.createElement(\"input\"); \r\n");
      out.write("       var i_goods_name = document.createElement(\"input\");\r\n");
      out.write("       var i_goods_price=document.createElement(\"input\");\r\n");
      out.write("       var i_goods_saleprice=document.createElement(\"input\");\r\n");
      out.write("       var i_goods_category=document.createElement(\"input\");\r\n");
      out.write("       /* var i_fileName=document.createElement(\"input\"); */\r\n");
      out.write("       /* var i_order_headcount=document.createElement(\"input\"); */\r\n");
      out.write("       \r\n");
      out.write("       i_goods_code.name=\"goods_code\";\r\n");
      out.write("       i_goods_name.name=\"goods_name\";\r\n");
      out.write("       i_goods_price.name=\"goods_price\";\r\n");
      out.write("       i_goods_saleprice.name=\"goods_saleprice\";\r\n");
      out.write("       i_goods_category.name=\"goods_category\";\r\n");
      out.write("       /* i_fileName.name=\"goods_fileName\"; */\r\n");
      out.write("       /* i_order_headcount.name=\"order_headcount\"; */\r\n");
      out.write("       \r\n");
      out.write("       i_goods_code.value=goods_code;\r\n");
      out.write("       /* i_order_headcount.value=order_headcount.value; */\r\n");
      out.write("       i_goods_name.value=goods_name;\r\n");
      out.write("       i_goods_price.value=goods_price;\r\n");
      out.write("       i_goods_saleprice.value=goods_saleprice;\r\n");
      out.write("       i_goods_category.value=goods_category;\r\n");
      out.write("       /* i_fileName.value=fileName; */\r\n");
      out.write("       \r\n");
      out.write("       formObj.appendChild(i_goods_code);\r\n");
      out.write("       formObj.appendChild(i_goods_name);\r\n");
      out.write("       formObj.appendChild(i_goods_price);\r\n");
      out.write("       formObj.appendChild(i_goods_saleprice);\r\n");
      out.write("       formObj.appendChild(i_goods_category);\r\n");
      out.write("       /* formObj.appendChild(i_fileName); */\r\n");
      out.write("       /* formObj.appendChild(i_order_goods_qty); */\r\n");
      out.write("   \r\n");
      out.write("       document.body.appendChild(formObj); \r\n");
      out.write("       formObj.method=\"post\";\r\n");
      out.write("       formObj.action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderEachGoods.do\";\r\n");
      out.write("       formObj.submit();\r\n");
      out.write("      }   \r\n");
      out.write("   </script>\r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("      #search {\r\n");
      out.write("         margin-bottom: 20px;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("      .date{\r\n");
      out.write("         padding-left:5px;\r\n");
      out.write("         border:none;\r\n");
      out.write("         background-color:#E0E0E0;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         height:20px;\r\n");
      out.write("      }\r\n");
      out.write("      .carousel-link .thumb {\r\n");
      out.write("         width: 25%;\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("         float: left;\r\n");
      out.write("      }\r\n");
      out.write("      .carousel-link .thumb img {\r\n");
      out.write("         width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      .carousel-link .thumb:first-of-type img {\r\n");
      out.write("         margin-left: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .carousel-link .thumb:last-of-type img {\r\n");
      out.write("         margin-right: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .thumb > * {\r\n");
      out.write("           height: calc(100% * var(--ratio));\r\n");
      out.write("       }\r\n");
      out.write("   </style>\r\n");
      out.write("   <script>\r\n");
      out.write("       $(function() {\r\n");
      out.write("           var firstImgHeight = $(\"#firstImg\").height();\r\n");
      out.write("           $(\".thumb > *\").css(\"--ratio\", firstImgHeight / 100 + \"\");\r\n");
      out.write("       });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class = \"container mt-4\">\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<input type=\"hidden\" name=\"isLogOn\" id=\"isLogOn\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isLogOn}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('/');
      out.write('>');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsHotelDetail.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/goods/goodsHotelDetail.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsHotelDetail.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsHotelDetail.jsp(172,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("hotel");
      // /WEB-INF/views/goods/goodsHotelDetail.jsp(172,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsHotelDetail.jsp(172,6) '${hotelList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${hotelList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("         <div class=\"container\">\r\n");
            out.write("             <div class=\"row\">\r\n");
            out.write("                 <div class=\"col-md-6\">\r\n");
            out.write("                     <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
            out.write("                         <div class=\"carousel-inner\">\r\n");
            out.write("                             <div class=\"carousel-item active\">\r\n");
            out.write("                                 <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/hotel/hotel1.jpg\">\r\n");
            out.write("                             </div>\r\n");
            out.write("                             <div class=\"carousel-item\">\r\n");
            out.write("                                 <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/hotel/hotel2.jpg\">\r\n");
            out.write("                             </div>\r\n");
            out.write("                             <div class=\"carousel-item\">\r\n");
            out.write("                                 <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/hotel/hotel3.jpg\">\r\n");
            out.write("                             </div>\r\n");
            out.write("                         </div>\r\n");
            out.write("                         <a class=\"carousel-control-prev\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
            out.write("                             <span class=\"carousel-control-prev-icon\"></span>\r\n");
            out.write("                         </a>\r\n");
            out.write("                         <a class=\"carousel-control-next\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
            out.write("                             <span class=\"carousel-control-next-icon\"></span>\r\n");
            out.write("                         </a>\r\n");
            out.write("                         <div class=\"clearfix\">\r\n");
            out.write("                             <div class=\"carousel-link\">\r\n");
            out.write("                                 <div data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"thumb\">\r\n");
            out.write("                                     <img id=\"firstImg\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/hotel/hotel1.jpg\" height = \"100%\">\r\n");
            out.write("                                 </div>\r\n");
            out.write("                                 <div data-target=\"#myCarousel\" data-slide-to=\"1\" class=\"thumb\">\r\n");
            out.write("                                     <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/hotel/hotel2.jpg\" height = \"100%\">\r\n");
            out.write("                                 </div>\r\n");
            out.write("                                 <div data-target=\"#myCarousel\" data-slide-to=\"2\" class=\"thumb\">\r\n");
            out.write("                                     <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/hotel/hotel3.jpg\" height = \"100%\">\r\n");
            out.write("                                 </div>\r\n");
            out.write("                             </div>\r\n");
            out.write("                         </div>\r\n");
            out.write("                     </div>\r\n");
            out.write("                 </div>\r\n");
            out.write("                 <div class=\"col-md-6\">\r\n");
            out.write("                     <h2>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\r\n");
            out.write("                     <h3>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<small>&nbsp;원 ~</small></h3>\r\n");
            out.write("                     <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_exp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                     <div class=\"row g-2\">\r\n");
            out.write("                     <div class=\"col-md\">\r\n");
            out.write("                          <div class=\"form-floating\">\r\n");
            out.write("                           <select class=\"form-select\" id=\"floatingSelect\" aria-label=\"Floating label select example\">\r\n");
            out.write("								<option value=\"1\">싱글</option>\r\n");
            out.write("								<option value=\"2\">더블</option>\r\n");
            out.write("								<option value=\"3\">디럭스 싱글</option>\r\n");
            out.write("								<option value=\"4\">디럭스 더블</option>\r\n");
            out.write("								<option value=\"5\">스위트 싱글</option>\r\n");
            out.write("								<option value=\"6\">스위트 더블</option>\r\n");
            out.write("                           </select>\r\n");
            out.write("                           <label for=\"floatingSelect\">객실 선택</label>\r\n");
            out.write("                        </div>\r\n");
            out.write("                     </div>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class = \"row g-2 mt-2 text-center\">\r\n");
            out.write("                     <p>총 금액</p>\r\n");
            out.write("                     <p>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" 원</p>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class = \"d-flex g-2 mt-2 mx-3\">\r\n");
            out.write("                     <a class=\"buy\" href = \"javascript:fn_order_each_goods('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_saleprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("');\">\r\n");
            out.write("                        <input type = \"button\" class=\"btn btn-primary\" value = \"바로 예약하기\">\r\n");
            out.write("                     </a>\r\n");
            out.write("                     <a class=\"cart\" href=\"javascript:add_cart('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("','order_goods_qty')\">\r\n");
            out.write("                        <input class=\"btn btn-primary btn-md\" data-bs-toggle=\"modal\" type = \"button\" value = \"장바구니에 담기\">\r\n");
            out.write("                     </a>\r\n");
            out.write("                  </div>\r\n");
            out.write("                 </div>\r\n");
            out.write("              </div>\r\n");
            out.write("          </div>\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/goods/goodsHotelDetail.jsp(230,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hotel.goods_saleprice}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsHotelDetail.jsp(230,24) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }
}
