/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-04-18 07:31:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsRentDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1675145507184L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675145505448L));
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>호텔 상품 조회</title>\r\n");
      out.write(" <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    //뭐지이거..??\r\n");
      out.write("   console.log('http://www.abdullahkahriman.com');\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap');\r\n");
      out.write("*{\r\n");
      out.write("   font-family: 'OTWelcomeRA';\r\n");
      out.write("   font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("/* 상품제목 위치조정 */\r\n");
      out.write(".rentDetailtitle{\r\n");
      out.write("   margin-left:300px;\r\n");
      out.write("}\r\n");
      out.write("/* hr태크 길이조정 */\r\n");
      out.write("hr{\r\n");
      out.write("   width:900px;\r\n");
      out.write("   margin-left:300px;\r\n");
      out.write("}\r\n");
      out.write("/* 상풍 이미지및 설명 위치조정 */\r\n");
      out.write(".rentmaintitle{\r\n");
      out.write("    float:left;\r\n");
      out.write("    height:300px;\r\n");
      out.write("}\r\n");
      out.write("/* 상품 이미지 좌측고정 */\r\n");
      out.write(".rentmaintitle img{\r\n");
      out.write("    float:left;\r\n");
      out.write("}\r\n");
      out.write("/* 상품 상세설명 위치조정 */\r\n");
      out.write(".rentmaintitle h5{\r\n");
      out.write("   margin-top:10px;\r\n");
      out.write("   margin-left:30px;\r\n");
      out.write("   float:left;\r\n");
      out.write("   width:1100px;\r\n");
      out.write("}\r\n");
      out.write("/* 아이콘및 설명 */\r\n");
      out.write(".minititle{\r\n");
      out.write("   margin:15px auto 15px 25px;\r\n");
      out.write("   float:left;\r\n");
      out.write("   width:550px;\r\n");
      out.write("}\r\n");
      out.write(".minititle tr td{\r\n");
      out.write("   float:left;\r\n");
      out.write("   width:300px;\r\n");
      out.write("}\r\n");
      out.write("/* 이용시간및 이하 내용 위치조정 */\r\n");
      out.write(".minititle1 li {\r\n");
      out.write("   margin: 5px auto 5px 25px;\r\n");
      out.write("   display : inline-block;\r\n");
      out.write("   width : 300px;\r\n");
      out.write("   list-style : none;\r\n");
      out.write("   font-size:12px;\r\n");
      out.write("   float:left;\r\n");
      out.write("}\r\n");
      out.write(".minititle1 li img{\r\n");
      out.write("   margin: auto 5px auto auto;\r\n");
      out.write("}\r\n");
      out.write("/* 운전자 정보입력칸 위치조정 */\r\n");
      out.write("#licensebox{\r\n");
      out.write("   margin:20px auto 20px 300px;\r\n");
      out.write("}\r\n");
      out.write("/* 지금예약버튼 위치조정 */\r\n");
      out.write("#button1{\r\n");
      out.write("   margin:20px auto 20px auto;   \r\n");
      out.write("}\r\n");
      out.write(".productmap{\r\n");
      out.write("    float:right;\r\n");
      out.write("    width:324.5px;\r\n");
      out.write("    height:355.5px;\r\n");
      out.write("    border:1px solid black;\r\n");
      out.write("    margin:-20px 10% auto auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsRentDetail.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/goods/goodsRentDetail.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsRentDetail.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsRentDetail.jsp(92,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("product");
      // /WEB-INF/views/goods/goodsRentDetail.jsp(92,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsRentDetail.jsp(92,1) '${carList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${carList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"rentDetailtitle\">\r\n");
            out.write("       <h4>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("       <hr>\r\n");
            out.write("   </div>\r\n");
            out.write("    <div class=\"rentmaintitle\">\r\n");
            out.write("      <img style=\"margin-left:15%;\" alt=\"소형이미지\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/car.png\" width=\"400px\" height=\"300px\">\r\n");
            out.write("      <div class=\"productmap\">\r\n");
            out.write("       <!-- 지도를 표시할 div 입니다 -->\r\n");
            out.write("      <div id=\"staticMap\" style=\"width:325px;height:355px;\"></div>\r\n");
            out.write("      \r\n");
            out.write("      <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=2e253b59d2cc8f52b94e061355413a9e\"></script>\r\n");
            out.write("      <script>\r\n");
            out.write("      var markers = [\r\n");
            out.write("          {\r\n");
            out.write("              position: new kakao.maps.LatLng(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_latitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_longitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\r\n");
            out.write("          },\r\n");
            out.write("          {\r\n");
            out.write("              position: new kakao.maps.LatLng(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_latitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_longitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("), \r\n");
            out.write("              text: '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" 위치입니다.' // text 옵션을 설정하면 마커 위에 텍스트를 함께 표시할 수 있습니다     \r\n");
            out.write("          }\r\n");
            out.write("      ];\r\n");
            out.write("\r\n");
            out.write("      var staticMapContainer  = document.getElementById('staticMap'), // 이미지 지도를 표시할 div  \r\n");
            out.write("          staticMapOption = { \r\n");
            out.write("              center: new kakao.maps.LatLng(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_latitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(',');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_longitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("), // 이미지 지도의 중심좌표\r\n");
            out.write("              level: 3, // 이미지 지도의 확대 레벨\r\n");
            out.write("              marker: markers // 이미지 지도에 표시할 마커 \r\n");
            out.write("          };    \r\n");
            out.write("      // 이미지 지도를 생성합니다\r\n");
            out.write("      var staticMap = new kakao.maps.StaticMap(staticMapContainer, staticMapOption);\r\n");
            out.write("      </script>\r\n");
            out.write("    </div>\r\n");
            out.write("   \r\n");
            out.write("      <table class=\"minititle\">\r\n");
            out.write("         <tr id=\"minititleOne\" style=\"list-style: none; display:inline-block;\">\r\n");
            out.write("            <td style=\"width:100px;\"><img alt=\"미니카\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/frontcar.png\" width=\"35px\" height=\"25px\">소형</td>\r\n");
            out.write("            <td style=\"width:100px;\"><img alt=\"좌석\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/seat.png\" width=\"35px\" height=\"25px\">4인승</td>\r\n");
            out.write("            <td style=\"width:105px;\"><img alt=\"핸들\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/handle.png\" width=\"35px\" height=\"25px\">자동변속</td>\r\n");
            out.write("            <td style=\"width:100px;\"><img alt=\"기름\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/gasoline.png\" width=\"35px\" height=\"25px\">휘발유</td>\r\n");
            out.write("         </tr>\r\n");
            out.write("      </table>\r\n");
            out.write("      <ul class=\"minititle1\">\r\n");
            out.write("         <li><img alt=\"캘린더\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/calender.png\" width=\"20px\" height=\"15px\">이용일 : <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></li>         \r\n");
            out.write("         <li><img alt=\"시계\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/watch.png\" width=\"20px\" height=\"15px\">이용 시간 : <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></li>\r\n");
            out.write("         <li><img alt=\"시계\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/watch.png\" width=\"20px\" height=\"15px\">인수 장소 : <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></li>\r\n");
            out.write("         <li><img alt=\"시계\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/watch.png\" width=\"20px\" height=\"15px\">반납 장소 : <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></li>\r\n");
            out.write("         <li><img alt=\"시계\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/watch.png\" width=\"20px\" height=\"15px\">대여가능 나이 : <span>26세이상</span></li>\r\n");
            out.write("         <li><img alt=\"시계\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/resources/image/rent/watch.png\" width=\"20px\" height=\"15px\">대여가능 운전경력 : <span>1년이상</span></li>\r\n");
            out.write("      </ul>\r\n");
            out.write("                    \r\n");
            out.write("   </div>\r\n");
            out.write("   <form id=\"main\">\r\n");
            out.write("   <div id=\"licensebox\">\r\n");
            out.write("      <h5>운전자 정보 입력</h5>\r\n");
            out.write("      <hr>\r\n");
            out.write("      <p>여권상의 영문성, 영문이름과 같지않으면 서비스가 거부될수 있습니다.</p>\r\n");
            out.write("      <div>\r\n");
            out.write("      <p>면허 번호</p>\r\n");
            out.write("      <input type=\"text\" name=\"license number\" placeholder=\"면허 번호를 입력해주세요.\">\r\n");
            out.write("      <p>발급 일자</p>\r\n");
            out.write("      <input type=\"text\" name=\"published date\" placeholder=\"예) 20150115\"><br>\r\n");
            out.write("      \r\n");
            out.write("      <button id=\"button1\" type=\"submit\">지금 예약</button>\r\n");
            out.write("      </div>\r\n");
            out.write("   </div>\r\n");
            out.write("   </form>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
