/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-04-18 07:30:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsFlightSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1675145507184L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675145505448L));
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>항공 목록 조회</title>\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.1.3/material.indigo-pink.min.css\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.1.3/material.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Optional JavaScript -->\r\n");
      out.write("<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css\">\r\n");
      out.write("<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker3.standalone.css'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	//출발지에따라 도착지가 변경되는창\r\n");
      out.write("	 function chageStartSelect(){ \r\n");
      out.write("	   \r\n");
      out.write("	   var selectList = document.getElementById(\"searchtitle1\")\r\n");
      out.write("	   \r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"김포\"){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"김해\"){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"제주\"){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"대구\"){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"사천\" || selectList.options[selectList.selectedIndex].value ==  \"포항/경주\" ||\r\n");
      out.write("	         selectList.options[selectList.selectedIndex].value == \"광주\" || selectList.options[selectList.selectedIndex].value == \"무안\" || \r\n");
      out.write("	         selectList.options[selectList.selectedIndex].value == '울산' ){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"횡성/원주\" || selectList.options[selectList.selectedIndex].value == \"군산\" ||\r\n");
      out.write("	         selectList.options[selectList.selectedIndex].value == \"청주\" ){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"여수\"){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"none\";\r\n");
      out.write("	   }\r\n");
      out.write("	   if(selectList.options[selectList.selectedIndex].value == \"양양\"){\r\n");
      out.write("	      alert(\"출발지가 설정되었습니다.\");\r\n");
      out.write("	      document.getElementById('searchtitletwo').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo1').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo2').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo3').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo4').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo5').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo6').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo7').style.display=\"none\";\r\n");
      out.write("	      document.getElementById('searchtitletwo8').style.display=\"\";\r\n");
      out.write("	   }\r\n");
      out.write("	  \r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write("	/* 왕복을눌렀을때 */\r\n");
      out.write("	function changelong(){\r\n");
      out.write("	   \r\n");
      out.write("	   var selectList = document.getElementById(\"search1\")\r\n");
      out.write("	        \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 편도를 눌렀을때 */\r\n");
      out.write("	function changesort(){\r\n");
      out.write("	   \r\n");
      out.write("	   var selectList = document.getElementById(\"search1\")\r\n");
      out.write("	   \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 편도 왕복 버튼 */\r\n");
      out.write("	function active(id){\r\n");
      out.write("	     if(activebutton != null){\r\n");
      out.write("	       document.getElementById(activebutton).style['background-color'] = '#eee';\r\n");
      out.write("	       document.getElementById(activebutton).style['color'] = '#000';\r\n");
      out.write("	     }\r\n");
      out.write("	    document.getElementById(id).style['background-color'] = '#8DE4FC';\r\n");
      out.write("	     document.getElementById(id).style['color'] = 'white';\r\n");
      out.write("	  \r\n");
      out.write("	     activebutton = id;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	#searchtitle1 , #searchtitletwo,#searchtitletwo1 , #searchtitletwo2 , #searchtitletwo3, #searchtitletwo4 , #searchtitletwo5 , #searchtitletwo6 , #searchtitletwo7 , #searchtitletwo8 , #tikey {\r\n");
      out.write("		width:250px;\r\n");
      out.write("		margin-right:30px;\r\n");
      out.write("		border:2px solid #4DD7F9;\r\n");
      out.write("		border-radius:5px;\r\n");
      out.write("		height:33px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#searchtitle1,#searchtitletwo , #searchtitletwo1 , #searchtitletwo2 , #searchtitletwo3 , #tikey, #searchtitletwo4 , #searchtitletwo5 , #searchtitletwo6 , #searchtitletwo7 , #searchtitletwo8 ,#searchtitletwo option {\r\n");
      out.write("		background-color:#8DE4FC;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#seatclass {\r\n");
      out.write("		background-color:#8DE4FC;\r\n");
      out.write("		border:2px solid #4DD7F9;\r\n");
      out.write("		border-radius:5px;\r\n");
      out.write("		height:33px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		vertical-align:center;\r\n");
      out.write("		color:black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#calender {\r\n");
      out.write("		background-color:#8DE4FC;\r\n");
      out.write("		border:2px solid #4DD7F9;\r\n");
      out.write("		border-radius:5px;\r\n");
      out.write("		height:33px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.productTag {\r\n");
      out.write("		margin:auto 10px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write(" \r\n");
      out.write("<form id=\"search1\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goods/goodsFlightKeyWordSearch.do\" method=\"get\">\r\n");
      out.write("   <div class = \"container\">\r\n");
      out.write("       <span>\r\n");
      out.write("        <select id=\"tikey\" name=\"tikey\" style=\"width:7%;\">\r\n");
      out.write("           <option value=\"1\">왕복</option>\r\n");
      out.write("           <option value=\"2\">편도</option>\r\n");
      out.write("      </select>\r\n");
      out.write("       \r\n");
      out.write("       <img class=\"icon\" alt=\"car_icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/flight/air.png\" width = \"25px\"> <!-- 검색창 왼쪽 비행기아이콘 -->\r\n");
      out.write("       <select id=\"searchtitle1\" name=\"searchtitle1\" onchange=\"chageStartSelect()\">\r\n");
      out.write("           <option value=\"1\" selected>출발지를 선택해주세요.</option>\r\n");
      out.write("           <option value=\"김포\">김포</option>\r\n");
      out.write("           <option value=\"김해\">김해</option>\r\n");
      out.write("           <option value=\"제주\">제주</option>\r\n");
      out.write("           <option value=\"대구\">대구</option>\r\n");
      out.write("           <option value=\"울산\">울산</option>\r\n");
      out.write("           <option value=\"청주\">청주</option>\r\n");
      out.write("           <option value=\"무안\">무안</option>\r\n");
      out.write("           <option value=\"광주\">광주</option>\r\n");
      out.write("           <option value=\"여수\">여수</option>\r\n");
      out.write("           <option value=\"포항/경주\">포항경주</option>\r\n");
      out.write("           <option value=\"양양\">양양</option>\r\n");
      out.write("           <option value=\"사천\">사천</option>\r\n");
      out.write("           <option value=\"군산\">군산</option>\r\n");
      out.write("           <option value=\"횡성/원주\">횡성/원주</option>\r\n");
      out.write("      </select>\r\n");
      out.write("       \r\n");
      out.write("        <img class=\"icon\" alt=\"car_icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/flight/air.png\" width = \"25px\">\r\n");
      out.write("       <select id=\"searchtitletwo\" name=\"searchtitletwo\">\r\n");
      out.write("           <option selected>도착지를 선택해주세요.</option>\r\n");
      out.write("      </select>\r\n");
      out.write("           <select id=\"searchtitletwo1\" name=\"searchtitletwo1\" style=\"display:none;\" onchange=\"seoul()\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option><!-- 서울이였을경우 -->\r\n");
      out.write("             <option value=\"광주\">광주</option>\r\n");
      out.write("           <option value=\"무안\">무안</option>\r\n");
      out.write("           <option value=\"부산/김해\">부산/김해</option>\r\n");
      out.write("           <option value=\"여수\">여수</option>\r\n");
      out.write("           <option value=\"울산\">울산</option>\r\n");
      out.write("           <option value=\"제주\">제주</option>\r\n");
      out.write("           <option value=\"진주/사천\">진주/사천</option>\r\n");
      out.write("           <option value=\"포항/경주\">포항/경주</option>\r\n");
      out.write("      </select> \r\n");
      out.write("    <select class=\"container\" id=\"searchtitletwo2\" name=\"searchtitletwo2\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 부산이였을경우 -->\r\n");
      out.write("           <option value=\"서울/김포\">서울/김포</option>\r\n");
      out.write("           <option value=\"제주\">제주</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      \r\n");
      out.write("      <select id=\"searchtitletwo3\" name=\"searchtitletwo3\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 제주일경우 -->\r\n");
      out.write("             <option value=\"광주\">광주</option>\r\n");
      out.write("           <option value=\"군산\">군산</option>\r\n");
      out.write("           <option value=\"대구\">대구</option>\r\n");
      out.write("           <option value=\"무안\">무안</option>\r\n");
      out.write("           <option value=\"울산\">울산</option>\r\n");
      out.write("           <option value=\"부산/김해\">부산/김해</option>\r\n");
      out.write("           <option value=\"서울/김포\">서울/김포</option>\r\n");
      out.write("           <option value=\"양양\">양양</option>\r\n");
      out.write("           <option value=\"여수\">여수</option>\r\n");
      out.write("           <option value=\"울산\">울산</option>\r\n");
      out.write("           <option value=\"원주\">원주</option>\r\n");
      out.write("           <option value=\"진주/사천\">진주/사천</option>\r\n");
      out.write("           <option value=\"청주\">청주</option>\r\n");
      out.write("           <option value=\"포항/경주\">포항/경주</option>\r\n");
      out.write("      </select>  \r\n");
      out.write("          \r\n");
      out.write("      <select id=\"searchtitletwo4\" name=\"searchtitletwo4\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 대구일경우 -->\r\n");
      out.write("             <option value=\"제주\">제주</option>\r\n");
      out.write("      </select>      \r\n");
      out.write("      <select id=\"searchtitletwo5\" name=\"searchtitletwo5\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 사천 , 포항/경주 , 광주 , 무안 , 울산일경우 -->\r\n");
      out.write("             <option value=\"서울/김포\">서울/김포</option>\r\n");
      out.write("             <option value=\"제주\">제주</option>\r\n");
      out.write("      </select>      \r\n");
      out.write("      <select id=\"searchtitletwo6\" name=\"searchtitletwo6\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 횡성/원주 ,  군산, 청주일경우 -->\r\n");
      out.write("             <option value=\"제주\">제주</option>\r\n");
      out.write("      </select>      \r\n");
      out.write("      <select id=\"searchtitletwo7\" name=\"searchtitletwo7\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 여수일경우 -->\r\n");
      out.write("             <option value=\"서울/김포\">서울/김포</option>\r\n");
      out.write("             <option value=\"양양\">양양</option>\r\n");
      out.write("             <option value=\"제주\">제주</option>\r\n");
      out.write("      </select>      \r\n");
      out.write("      <select id=\"searchtitletwo8\" name=\"searchtitletwo8\" style=\"display:none;\">\r\n");
      out.write("           <option value=\"\" selected>도착지를 선택해주세요.</option> <!-- 양양일경우 -->\r\n");
      out.write("             <option value=\"여수\">여수</option>\r\n");
      out.write("             <option value=\"제주\">제주</option>\r\n");
      out.write("      </select>      \r\n");
      out.write("      <select id=\"seatclass\" name=\"seatclass\">\r\n");
      out.write("            <option selected>좌석등급</option>\r\n");
      out.write("             <option value=\"1\">일등석</option>\r\n");
      out.write("             <option value=\"2\">비즈니스</option>\r\n");
      out.write("             <option value=\"3\">이코노미</option>\r\n");
      out.write("      </select> \r\n");
      out.write("     <div class = \"container\">\r\n");
      out.write("		<div class=\"input-daterange input-group\" id=\"flight-datepicker\">\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<!-- <label>출발일</label> -->\r\n");
      out.write("				<span class=\"fontawesome-calendar\"></span>\r\n");
      out.write("				<input class=\"input-sm form-control\" type=\"text\" id=\"start-date\" name=\"start\" placeholder=\"출발일을 선택하세요\" data-date-format=\"DD, MM d\"/>\r\n");
      out.write("				<span class=\"date-text date-depart\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-item\">\r\n");
      out.write("				<!-- <label>도착일</label> -->\r\n");
      out.write("				<span class=\"fontawesome-calendar\"></span>\r\n");
      out.write("				<input class=\"input-sm form-control\" type=\"text\" id=\"end-date\" name=\"end\" placeholder=\"도착일을 선택하세요\" data-date-format=\"DD, MM d\"/>\r\n");
      out.write("				<span class=\"date-text date-return\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div> \r\n");
      out.write("       <button type=\"submit\" class=\"btn btn-link\" id=\"lastbtn\">\r\n");
      out.write("        <img class=\"icon\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/flight/search.png\" alt=\"검색\"    width=\"20px\" height=\"20px\"> <!-- submit 검색버튼 -->\r\n");
      out.write("  </button>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- 본문 상품 -->\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- partial -->\r\n");
      out.write("	<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'></script>\r\n");
      out.write("	<script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js'></script>\r\n");
      out.write("	<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery-dateFormat/1.0/jquery.dateFormat.js'></script>\r\n");
      out.write("	<script  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/jquery/script.js\"></script>\r\n");
      out.write("   <!-- JavaScript Bundle with Popper -->\r\n");
      out.write("   <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsFlightSearch.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(328,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("product");
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(328,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/goods/goodsFlightSearch.jsp(328,0) '${keyword}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${keyword}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\r');
            out.write('\n');
            out.write('	');
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(329,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_category == '항공' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<form class=\"container row col\" style=\"text-align:center; margin-left:11%;\">\r\n");
          out.write("		   <div id=\"product_center\" class=\"container d-flex align-items-end justify-content-center\" style=\"margin:10px auto;\">\r\n");
          out.write("			   <p style=\"margin:0px;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p> <!-- 항공사이름 -->\r\n");
          out.write("			   <img alt=\"가격할인배너이미지\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/image/flight/sale.png\" width=\"30px\" height=\"25px\"> <!-- 가격 할인 이미지 -->\r\n");
          out.write("			   <img alt=\"가격할인배너이미지\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/image/flight/Mileagelogo.jpg\" width=\"100px\" height=\"25px\"> <!-- 가격 할인 이미지 -->\r\n");
          out.write("			   <img alt=\"가격할인배너이미지\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/image/flight/sale2.png\" width=\"25px;\" height=\"25px\"> <!-- 가격 할인 이미지 -->\r\n");
          out.write("			    <span class=\"product_time\"><span class=\"productTag\">");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</span><span class=\"productTag\">");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</span><span class=\"productTag\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_departures}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("공항</span>\r\n");
          out.write("				    <img alt=\"air_mini\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/image/flight/air.png\" width=\"15px\" height=\"15px\">\r\n");
          out.write("				    <span class=\"productTag\">");
          if (_jspx_meth_fmt_005fformatDate_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</span><span class=\"productTag\">");
          if (_jspx_meth_fmt_005fformatDate_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</span><span class=\"productTag\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_arrivals}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("공항</span>\r\n");
          out.write("				    <span class=\"product_price\">가격 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_saleprice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("원</span>\r\n");
          out.write("				       <span class=\"button_css\">\r\n");
          out.write("				         <button type=\"submit\">지금예약</button>\r\n");
          out.write("				         <button type=\"submit\">장바구니</button>\r\n");
          out.write("				      </span>\r\n");
          out.write("			   </span>\r\n");
          out.write("		   </div>\r\n");
          out.write("		   <hr id=\"product_hr\">\r\n");
          out.write("		</form>   \r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(336,59) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_departure_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(336,59) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(336,169) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_departure_time}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(336,169) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("HH-SS");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(338,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_arrival_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(338,33) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f2.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f2 = _jspx_th_fmt_005fformatDate_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f2);
      _jspx_th_fmt_005fformatDate_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(338,141) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.goods_arrival_time}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/goods/goodsFlightSearch.jsp(338,141) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f3.setPattern("HH-SS");
      int _jspx_eval_fmt_005fformatDate_005f3 = _jspx_th_fmt_005fformatDate_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f3);
      _jspx_th_fmt_005fformatDate_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f3_reused);
    }
    return false;
  }
}
