/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-04-20 03:32:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.joinandlogin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginFormCom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/maven-kimminseon/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cornertocorner/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675145505448L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@use postcss-preset-env;\r\n");
      out.write("@import url(https://meyerweb.com/eric/tools/css/reset/reset.css);\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("   /* background: #f4f4f4; */\r\n");
      out.write("   color: #5a5656;\r\n");
      out.write("  display: grid;\r\n");
      out.write("  line-height: 1.5;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  min-height: 100vh;\r\n");
      out.write("  place-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a { text-decoration: none; }\r\n");
      out.write("\r\n");
      out.write("h1 { font-size: 1em; }\r\n");
      out.write("\r\n");
      out.write("h1, p {\r\n");
      out.write("   margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("strong {\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uppercase { text-transform: uppercase; }\r\n");
      out.write("\r\n");
      out.write("/* ---------- LOGIN ---------- */\r\n");
      out.write("\r\n");
      out.write("#login {\r\n");
      out.write("   margin: 50px auto;\r\n");
      out.write("   width: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form fieldset input[type=\"text\"],\r\n");
      out.write("input[type=\"password\"] {\r\n");
      out.write("  appearance: none;\r\n");
      out.write("   background: #e5e5e5;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 3px;\r\n");
      out.write("   color: #5a5656;\r\n");
      out.write("   font-family: inherit;\r\n");
      out.write("   font-size: 14px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   outline: none;\r\n");
      out.write("   padding: 0px 10px;\r\n");
      out.write("   width: 280px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form fieldset input[type=\"submit\"] {\r\n");
      out.write("  appearance: none;\r\n");
      out.write("   background-color: #008dde;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 3px;\r\n");
      out.write("   color: #f4f4f4;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   font-family: inherit;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   text-transform: uppercase;\r\n");
      out.write("   width: 280px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form fieldset a {\r\n");
      out.write("   color: #5a5656;\r\n");
      out.write("   font-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form fieldset a:hover { text-decoration: underline; }\r\n");
      out.write("\r\n");
      out.write(".btn-round {\r\n");
      out.write("   background: #5a5656;\r\n");
      out.write("   border-radius: 50%;\r\n");
      out.write("   color: #f4f4f4;\r\n");
      out.write("   display: block;\r\n");
      out.write("   font-size: 12px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   line-height: 50px;\r\n");
      out.write("   margin: 30px 125px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   text-transform: uppercase;\r\n");
      out.write("   width: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".facebook-before {\r\n");
      out.write("   background: #0064ab;\r\n");
      out.write("   border-radius: 3px 0px 0px 3px;\r\n");
      out.write("   color: #f4f4f4;\r\n");
      out.write("   display: block;\r\n");
      out.write("   float: left;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   line-height: 50px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   width: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".facebook {\r\n");
      out.write("   background: #0079ce;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 0px 3px 3px 0px;\r\n");
      out.write("   color: #f4f4f4;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   text-transform: uppercase;\r\n");
      out.write("   width: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".twitter-before {\r\n");
      out.write("   background: #189bcb;\r\n");
      out.write("   border-radius: 3px 0px 0px 3px;\r\n");
      out.write("   color: #f4f4f4;\r\n");
      out.write("   display: block;\r\n");
      out.write("   float: left;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   line-height: 50px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   width: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".twitter {\r\n");
      out.write("   background: #1bb2e9;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 0px 3px 3px 0px;\r\n");
      out.write("   color: #f4f4f4;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   text-transform: uppercase;\r\n");
      out.write("   width: 230px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"login\">\r\n");
      out.write("\r\n");
      out.write("  <h1><strong>사업체 로그인</strong></h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/joinAndLogin/loginCom.do\" method=\"post\" >\r\n");
      out.write("	\r\n");
      out.write("    <fieldset>\r\n");
      out.write("\r\n");
      out.write("      <p><input type=\"text\" placeholder=\"아이디\" name=\"com_id\" required></p>\r\n");
      out.write("\r\n");
      out.write("      <p><input type=\"password\" placeholder=\"비밀번호\" name=\"com_pw\" required></p>\r\n");
      out.write("      \r\n");
      out.write("      <p><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/joinAndLogin/searchIdCom.do\">아이디 찾기</a> | <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/joinAndLogin/searchPwCom.do\">비밀번호 찾기</a> | <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberForm.do\">회원가입</a></p>\r\n");
      out.write("      <p><input type=\"submit\" value=\"로그인\"></p>\r\n");
      out.write("\r\n");
      out.write("    </fieldset>\r\n");
      out.write("\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <p><span class=\"btn-round\">or</span></p>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/joinandlogin/loginFormCom.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/joinandlogin/loginFormCom.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/joinandlogin/loginFormCom.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/joinandlogin/loginFormCom.jsp(10,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<script>\r\n");
          out.write("window.onload=function()\r\n");
          out.write("{\r\n");
          out.write("  result();\r\n");
          out.write("}\r\n");
          out.write("\r\n");
          out.write("function result(){\r\n");
          out.write("   alert(\"아이디나  비밀번호가 틀립니다. 다시 로그인해주세요\");\r\n");
          out.write("}\r\n");
          out.write("\r\n");
          out.write("</script>\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
